theme = "onedark"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-b = ":bc!"

[keys.normal.space]
t = [
  ":insert-output \"grep %{buffer_name} -e 'TODO' -Hn || echo 'No TODOs found'\"",
  "delete_selection",
  ":n",
  "paste_after"
]

[keys.insert]
C-t = "@<esc>bc<S-lt><space><esc>h<S-R>li<S-gt><ret><S-lt>/<space><esc>h<S-R>li<S-gt><esc>kglli<ret>"
C-y = "@<esc>bc<S-lt><space><esc>h<S-R>li<S-gt><S-lt>/<space><esc>h<S-R>li<S-gt><esc>F<S-lt>i"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
